export const dataproduct = [
  {
    id: 1,
    kode_sku: 'SKU001',
    nama_produk: 'Rokok Marlboro with Marijuana',
    harga_beli: '25000',
    harga_jual: '35000',
    nama_satuan: 'pcs',
  },
  {
    id: 2,
    kode_sku: 'SKU002',
    nama_produk: 'Rokok Dji Sam Soe',
    harga_beli: '20000',
    harga_jual: '25000',
    nama_satuan: 'pcs',
  },
  {
    id: 3,
    kode_sku: 'SKU003',
    nama_produk: 'Pulpy Orange',
    harga_beli: '4000',
    harga_jual: '5000',
    nama_satuan: 'pcs',
  },
  {
    id: 4,
    kode_sku: 'SKU004',
    nama_produk: 'Kopi Kapal Api 150gr',
    harga_beli: '14000',
    harga_jual: '17000',
    nama_satuan: 'pcs',
  },
  {
    id: 5,
    kode_sku: 'SKU005',
    nama_produk: 'Kopi Ayam Merak 150gr',
    harga_beli: '15000',
    harga_jual: '18000',
    nama_satuan: 'pcs',
  },
  {
    id: 6,
    kode_sku: 'SKU006',
    nama_produk: 'Kecap Bango 100 gr',
    harga_beli: '5000',
    harga_jual: '6000',
    nama_satuan: 'pcs',
  },
  {
    id: 7,
    kode_sku: 'SKU007',
    nama_produk: 'Kecap Bango 100 gr',
    harga_beli: '5800',
    harga_jual: '7000',
    nama_satuan: 'pcs',
  },
  {
    id: 8,
    kode_sku: 'SKU008',
    nama_produk: 'Kecap ABC 100 gr',
    harga_beli: '5500',
    harga_jual: '6500',
    nama_satuan: 'pcs',
  },
  {
    id: 9,
    kode_sku: 'SKU009',
    nama_produk: 'Aqua Botol 100 ml',
    harga_beli: '4000',
    harga_jual: '5000',
    nama_satuan: 'pcs',
  },
  {
    id: 10,
    kode_sku: 'SKU010',
    nama_produk: 'Aqua Botol 1000 ml',
    harga_beli: '8000',
    harga_jual: '10000',
    nama_satuan: 'pcs',
  },
];
